spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ebankify
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
security:
  user:
    password: "{bcrypt}"
